# Generated by Django 5.0.6 on 2026-05-14 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/business_logos/'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='sort_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffpayrate',
            name='per_head_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-attendee rate used for per_head and blended rate types.', max_digits=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='cover_reliability_score',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Separate score tracking cover-specific reliability.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='priority_tier',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cover dispatch priority: 1 = first offered, 3 = last offered.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='staffpayrate',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Base rate (per_class, base for blended, or flat hourly)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffpayrate',
            name='rate_type',
            field=models.CharField(choices=[('per_class', 'Per Class'), ('per_head', 'Per Head'), ('blended', 'Blended (Base + Per Head)'), ('hourly', 'Hourly'), ('flat', 'Flat')], default='per_class', max_length=20),
        ),
    ]
