# Generated by Django 5.0.6 on 2026-05-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffavailability_unique_per_slot'),
        ('tenants', '0003_tenant_stripe_signup_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffavailability',
            unique_together={('staff', 'day_of_week', 'site')},
        ),
    ]
