# Generated by Django 5.0.6 on 2026-06-04 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staffprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.ForeignKey(help_text="The person's global login. One user can have a staff profile per gym.", on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
