# Generated by Django 5.0.6 on 2026-05-14 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_paymentdetails_additional_notes_and_more'),
        ('tenants', '0001_initial'),
        ('timetable', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classbonus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classbonus',
            name='bonus_type',
            field=models.CharField(choices=[('flat_bonus', 'Flat Bonus (always)'), ('attendance_threshold', 'Attendance Threshold (if attendance ≥ N)'), ('per_head_above', 'Per Head Above Threshold')], default='flat_bonus', max_length=30),
        ),
        migrations.AddField(
            model_name='classbonus',
            name='name',
            field=models.CharField(blank=True, help_text='Label shown on invoice line item.', max_length=200),
        ),
        migrations.AddField(
            model_name='classbonus',
            name='threshold',
            field=models.PositiveIntegerField(default=0, help_text='Minimum attendance for attendance_threshold; base count for per_head_above.'),
        ),
        migrations.AddField(
            model_name='timetableevent',
            name='amber_threshold_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableevent',
            name='archive_status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='timetableevent',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='timetableevent',
            name='green_threshold_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableevent',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Admin-only notes, not visible to instructors.'),
        ),
        migrations.AddField(
            model_name='timetableevent',
            name='original_instructor',
            field=models.ForeignKey(blank=True, help_text='Instructor before cover was applied.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_events', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='timetableevent',
            name='purple_threshold_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableevent',
            name='recurring_pattern_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups all instances of a recurring series.', null=True),
        ),
        migrations.AlterField(
            model_name='classbonus',
            name='threshold_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='timetableevent',
            index=models.Index(fields=['tenant', 'archive_status'], name='timetable_e_tenant__c7ac02_idx'),
        ),
    ]
