# Generated by Django 5.0.6 on 2026-05-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_classbonus_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='color',
            field=models.CharField(default='#6b7280', max_length=7),
        ),
    ]
