# Generated by Django 5.0.6 on 2026-06-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_add_color_to_classtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableevent',
            name='pending_instructor_email',
            field=models.EmailField(blank=True, db_index=True, help_text='Set during CSV import when a row names an instructor email that has no StaffProfile yet. The staff import back-fills the instructor and clears this. Lets staff/timetable CSVs be imported in any order.', max_length=254),
        ),
    ]
