# Generated by Django 5.0.6 on 2026-10-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_timetableevent_pending_instructor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtimetablerule',
            name='end_time',
            field=models.TimeField(blank=True, help_text="Null = start_time + the class type's duration.", null=True),
        ),
        migrations.AddField(
            model_name='recurringtimetablerule',
            name='series_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Shared by every rule created together (e.g. a Mon + Wed class), and stamped on their events as recurring_pattern_id.', null=True),
        ),
    ]
