# Generated by Django 5.0.6 on 2026-05-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='business_phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='_access_token_encrypted',
            field=models.TextField(blank=True, db_column='access_token_encrypted', default=''),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='phone_number_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='waba_id',
            field=models.CharField(blank=True, default='', help_text='WhatsApp Business Account ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappaccount',
            name='webhook_verify_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
