# Generated by Django 5.0.6 on 2026-05-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='_notification_email_password',
            field=models.TextField(blank=True, db_column='notification_email_password', default=''),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='notification_from_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='notification_from_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
