# Generated by Django 5.0.6 on 2026-05-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_stripe_signup_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=10),
        ),
    ]
