# Generated by Django 5.0.6 on 2026-06-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_currency_symbol_to_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='cover_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='invoice_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
