# Generated by Django 5.0.6 on 2026-06-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_notification_toggle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='cover_auto_dispatch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='cover_critical_threshold_hours',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
