# Generated by Django 5.0.6 on 2026-06-11 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenantsettings_cover_auto_dispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='pay_period_anchor_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
