# Generated by Django 5.0.6 on 2026-05-14 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cover', '0001_initial'),
        ('staff', '0001_initial'),
        ('tenants', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absence',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='absence',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='absence',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coveroffer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coveroffer',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_offers', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='coveroffer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='coveroffer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='absence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_requests', to='cover.absence'),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='timetable_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_requests', to='timetable.timetableevent'),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coveroffer',
            name='cover_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='cover.coverrequest'),
        ),
        migrations.AddField(
            model_name='coverresponse',
            name='cover_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cover.coveroffer'),
        ),
        migrations.AddIndex(
            model_name='coverrequest',
            index=models.Index(fields=['tenant', 'status'], name='cover_reque_tenant__720afe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coveroffer',
            unique_together={('cover_request', 'staff')},
        ),
    ]
