# Generated by Django 5.0.6 on 2026-06-01 03:29

import apps.cover.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0003_coverrequest_cancellation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveroffer',
            name='accept_code',
            field=models.CharField(db_index=True, default=apps.cover.models._generate_accept_code, max_length=16),
        ),
    ]
