# Generated by Django 5.0.6 on 2026-06-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0004_increase_accept_code_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='open', max_length=20),
        ),
    ]
