# Generated by Django 5.0.6 on 2026-06-10 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0005_expire_status'),
        ('staff', '0007_alter_staffprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coverrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_cover_requests', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cover_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='critical_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_cover_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coverrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('denied', 'Denied'), ('open', 'Open'), ('offered', 'Offered'), ('critical', 'Critical'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='open', max_length=20),
        ),
    ]
