# Generated by Django 5.0.6 on 2026-05-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('notification_type', models.CharField(choices=[('cover_request', 'Cover Request'), ('cover_accepted', 'Cover Accepted'), ('invoice_submitted', 'Invoice Submitted'), ('invoice_approved', 'Invoice Approved'), ('invoice_rejected', 'Invoice Rejected'), ('invoice_paid', 'Invoice Paid'), ('class_cancelled', 'Class Cancelled'), ('class_reminder', 'Class Reminder'), ('system', 'System')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('notification_type', models.CharField(max_length=30)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('whatsapp', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_preference',
            },
        ),
    ]
